version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  install_dependencies:
    <<: *defaults

    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths: ["node_modules"]
          key: dependency-cache-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths: ["repo"]

  tests_lint:
    <<: *defaults

    docker:
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

  publish:
    <<: *defaults

    docker:
      - image: circleci/node:10.16.3
    steps:
    - attach_workspace:
          at: ~/
    - run:
        name: Authenticate with nexus
        command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
    - add_ssh_keys:
        fingerprints:
          - "da:05:68:71:6f:2f:0d:d0:2c:84:1d:a8:be:3f:28:79"
    - run: git config --global user.email circleci@circleci
    - run: git config --global user.name CircleCI
    - run: yarn lerna:publish

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install_dependencies

      - tests_lint:
          requires:
            - install_dependencies

      - publish:
          context: NEXUS
          requires:
            - tests_lint
          filters:
            branches:
              only: ["master"]
