version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn coverage
      - store_artifacts:
          path: coverage
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run: yarn pub
