version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run: git config --global -l #<- totally unnecessary, but "fixes" problem?
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: yarn pub
